### ISSUE TITLE
In Anki version >2.1.50 it doesn't show the "add cloze" button

### ISSUE THREAD

**Issue by Ompexbr** [RisingOrange/basic2cloze#4]
# Bug report
When I update to version > 2.1.50, it doesn't show the add cloze button. 
![image](https://user-images.githubusercontent.com/54576432/173660008-daf67cd8-9cea-4672-8cd8-3e1b6716c91b.png)

**Comment by RisingOrange** [comment]
Fixed it! The new version is on AnkiWeb.
